openapi: 3.0.1
info:
  title: Statistics
  version: '2.18'
  description: 'Methods to get different reports. For Paid storage report, send a
    request to generate it, and then a request to get it. other report are available
    immediately, without pre-generation.

    '
security:
  - HeaderApiKey: []
x-tags:
  - name: Statistics
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
  responses:
    200SuccessDownloadedFiles:
      description: Success
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ResponsePaidStorage'
    400BadRequest:
      description: Incorrect request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    429TooManyRequests:
      description: Too many requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    500InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    404EntityNotFound:
      description: Path not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: string
    DownloadRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          description: Task ID
    responseErrorStatistics:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    Response429:
      type: object
      properties:
        code:
          description: ''
          type: integer
        message:
          description: ''
          type: string
    IncomesItem:
      type: object
      properties:
        incomeId:
          type: integer
          description: Supply number
        number:
          type: string
          maxLength: 40
          description: Universal transfer document number
        date:
          type: string
          format: date
          description: Receipt date. If the time zone is not specified, then Moscow
            time UTC+3 is taken.
        lastChangeDate:
          type: string
          format: date-time
          description: Date and time of refreshing info of service. This field corresponds
            to the `dateFrom` parameter in the request. If the time zone is not specified,
            then Moscow time UTC+3 is taken.
        supplierArticle:
          type: string
          maxLength: 75
          description: Supplier article
        techSize:
          type: string
          maxLength: 30
          description: Product size (eg S, M, L, XL, 42, 42-43)
        barcode:
          type: string
          maxLength: 30
          description: Barcode
        quantity:
          type: integer
          description: Quantity
        totalPrice:
          type: number
          description: Total price
        dateClose:
          type: string
          format: date
          description: Date of closing in WB. If the time zone is not specified, then
            Moscow time UTC+3 is taken.
        warehouseName:
          type: string
          maxLength: 50
          description: Name of warehouse
        nmId:
          type: integer
          description: WB article
        status:
          type: string
          maxLength: 50
          enum:
            - Accepted
          description: Current supply status
    StocksItem:
      type: object
      properties:
        lastChangeDate:
          type: string
          format: date-time
          description: Date and time of refreshing info of service. This field corresponds
            to the `dateFrom` parameter in the request. If the time zone is not specified,
            then Moscow time UTC+3 is taken.
        warehouseName:
          type: string
          maxLength: 50
          description: Name of warehouse
        supplierArticle:
          type: string
          maxLength: 75
          description: Supplier article
        nmId:
          type: integer
          description: WB article
        barcode:
          type: string
          maxLength: 30
          description: Barcode
        quantity:
          type: integer
          description: Quantity available for sale (how many can be added to cart)
        inWayToClient:
          type: integer
          description: On the way to the customer
        inWayFromClient:
          type: integer
          description: On the way from the client
        quantityFull:
          type: integer
          description: Total (unsold) quantity that is in stock (= `quantity` + in
            transit)
        category:
          type: string
          maxLength: 50
          description: Category
        subject:
          type: string
          maxLength: 50
          description: Subject
        brand:
          type: string
          maxLength: 50
          description: Brand
        techSize:
          type: string
          maxLength: 30
          description: Product size (eg S, M, L, XL, 42, 42-43)
        Price:
          type: number
          description: Price
        Discount:
          type: number
          description: Discount
        isSupply:
          type: boolean
          description: Supply contract (internal process data)
        isRealization:
          type: boolean
          description: Implementation contract (internal process data)
        SCCode:
          type: string
          maxLength: 50
          description: Contract code (internal process data)
    OrdersItem:
      type: object
      properties:
        gNumber:
          type: string
          maxLength: 50
          description: Order number. Combines all items of one order.
        date:
          type: string
          format: date-time
          description: Date and time of order. This field equals to `dateFrom` in
            request if `flag=1`. If the time zone is not specified, then Moscow time
            UTC+3 is taken.
        lastChangeDate:
          type: string
          format: date-time
          description: Date and time of refreshing info of service. This field corresponds
            to the `dateFrom` parameter in the request if the `flag=0` parameter exist
            or not specified. If the time zone is not specified, then Moscow time
            UTC+3 is taken.
        supplierArticle:
          type: string
          maxLength: 75
          description: Supplier article
        techSize:
          type: string
          maxLength: 30
          description: Product size (eg S, M, L, XL, 42, 42-43)
        barcode:
          type: string
          maxLength: 30
          description: Barcode
        totalPrice:
          type: number
          description: Agreed price without discounts. You should use `priceWithDiscount
            = totalPrice * (1 - discountPercent/100)` formula for get price with discount.
        discountPercent:
          type: integer
          description: Agreed final discount. If you apply this parameter to the `totalPrice`,
            it will give the amount to be paid.
        warehouseName:
          type: string
          maxLength: 50
          description: Shipping warehouse name
        oblast:
          type: string
          maxLength: 200
          description: Area
        incomeID:
          type: integer
          description: Supply number (from seller to warehouse)
        odid:
          type: integer
          description: Unique ID for order position. That parameter may use for find
            matches between orders and sales.
        nmId:
          type: integer
          description: WB article
        subject:
          type: string
          maxLength: 50
          description: Subject
        category:
          type: string
          maxLength: 50
          description: Category
        brand:
          type: string
          maxLength: 50
          description: Brand
        isCancel:
          type: boolean
          description: Order canceling. true - order was canceled before payment.
        cancel_dt:
          type: string
          format: date-time
          description: Date and time for order canceling. If order wasn't canceled,
            then `"0001-01-01T00:00:00"`. If the time zone is not specified, then
            Moscow time UTC+3 is taken.
        sticker:
          type: string
          description: The digital value of the sticker that is attached to the product
            during the order assembly process using the Marketplace system.
        srid:
          type: string
          description: 'Unique order ID. <br> Note for those working with Marketplace
            API: `srid` equals `rid` in response of orders methods.

            '
        orderType:
          type: string
          description: 'The type of the received order <br> <dl> <dt>Possible values:</dt>
            <dd>Клиентский - "The order received from the buyer."</dd> <dd>Возврат
            Брака - "Return of the goods to the seller."</dd> <dd>Принудительный возврат
            - "Return of the goods to the seller."</dd> <dd>Возврат обезлички - "Return
            of the goods to the seller."</dd> <dd>Возврат Неверного Вложения - "Return
            of the goods to the seller."</dd> <dd>Возврат Продавца - "Return of the
            goods to the seller."</dd> </dl>

            '
    SalesItem:
      type: object
      properties:
        date:
          type: string
          format: date-time
          description: Date and time of sale. This field equals to `dateFrom` in request
            if `flag`=1. If the time zone is not specified, then Moscow time (UTC+3)
            is taken.
        lastChangeDate:
          type: string
          format: date-time
          description: Date and time of refreshing info of service. This field corresponds
            to the `dateFrom` parameter in the request if the `flag`=0 parameter exist
            or not specified. If the time zone is not specified, then Moscow time
            (UTC+3) is taken.
        warehouseName:
          type: string
          maxLength: 50
          description: Shipping warehouse
        countryName:
          type: string
          maxLength: 200
          description: Country
        oblastOkrugName:
          type: string
          maxLength: 200
          description: Area
        regionName:
          type: string
          maxLength: 200
          description: Region
        supplierArticle:
          type: string
          maxLength: 75
          description: Supplier article
        nmId:
          type: integer
          description: WB article
        barcode:
          type: string
          maxLength: 30
          description: Barcode
        category:
          type: string
          maxLength: 50
          description: Category
        subject:
          type: string
          maxLength: 50
          description: Subject
        brand:
          type: string
          maxLength: 50
          description: Brand
        techSize:
          type: string
          maxLength: 30
          description: Product size
        incomeID:
          type: integer
          description: Supply number
        isSupply:
          type: boolean
          description: Supply contract
        isRealization:
          type: boolean
          description: Implementation contract
        totalPrice:
          type: number
          description: Price without discounts
        discountPercent:
          type: integer
          description: Seller's discount
        spp:
          type: number
          description: WB discount
        forPay:
          type: number
          description: To transfer to the supplier
        finishedPrice:
          type: number
          description: The actual price including all discounts (to be charged to
            the buyer)
        priceWithDisc:
          type: number
          description: Price with seller's discount, from which the amount to be transferred
            to the seller is calculated according to the following formula `forPay`
            (= `totalPrice` * (1 - `discountPercent`/100))
        saleID:
          type: string
          maxLength: 15
          description: 'The unique ID of the sale/refund. <ul>  <li> `SXXXXXXXXXX`
            — sale  <li> `RXXXXXXXXXX` — refund  </ul>

            '
        orderType:
          type: string
          description: 'Order type <ul> <li> `Клиентский` - an order received from
            a customer <li> `Возврат Брака` - return the item to the seller <li> `Принудительный
            возврат` - return the goods to the seller <li> `Возврат обезлички` - return
            the item to the seller <li> `Возврат Неверного Вложения` - return the
            item to the seller <li> `Возврат Продавца` - return the goods to the seller          </ul>

            '
        sticker:
          type: string
          description: sticker ID
        gNumber:
          type: string
          maxLength: 50
          description: Order number
        odid:
          type: integer
          description: The unique ID of the order item
        srid:
          type: string
          description: 'Unique order ID. <br> Note for those working with Marketplace
            API: `srid` equals `rid` in response of orders methods.

            '
    DetailReportItem:
      type: object
      properties:
        realizationreport_id:
          example: 1234567
          type: integer
          description: Report number
        date_from:
          example: '2022-10-17T00:00:00Z'
          type: string
          format: date-time
          description: Start date of the reporting period
        date_to:
          example: '2022-10-23T00:00:00Z'
          type: string
          format: date-time
          description: End date of the reporting period
        create_dt:
          example: '2022-10-24T14:40:32'
          type: string
          format: date-time
          description: Report generation date
        currency_name:
          example: руб
          type: string
          description: Currency of report
        suppliercontract_code:
          example: null
          type: object
          description: Contract
        rrd_id:
          example: 1232610467
          type: integer
          description: Row number
        gi_id:
          example: 123456
          type: integer
          description: Supply number
        subject_name:
          example: Mini ovens
          type: string
          description: Subject
        nm_id:
          example: 1234567
          type: integer
          description: WB article
        brand_name:
          example: BlahBlah
          type: string
          description: Brand
        sa_name:
          example: MAB123
          type: string
          description: Seller's article
        ts_name:
          example: '0'
          type: string
          description: Size
        barcode:
          example: '1231312352310'
          type: string
          description: Barcode
        doc_type_name:
          example: Продажа
          type: string
          description: Document type
        quantity:
          type: integer
          example: 1
          description: Quantity
        retail_price:
          example: 1249
          type: number
          description: Retail price
        retail_amount:
          example: 367
          type: number
          description: Sales amount (refunds)
        sale_percent:
          example: 68
          type: integer
          description: Agreed discount
        commission_percent:
          example: 0.1324
          type: number
          description: Commission percentage
        office_name:
          example: Коледино
          type: string
          description: Warehouse
        supplier_oper_name:
          example: Продажа
          type: string
          description: Reason for payment
        order_dt:
          example: '2022-10-13T00:00:00Z'
          type: string
          format: date-time
          description: Date of order. <br> Sent with an explicit indication of the
            time zone
        sale_dt:
          example: '2022-10-20T00:00:00Z'
          type: string
          format: date-time
          description: Dte of sale. <br> Sent with an explicit indication of the time
            zone
        rr_dt:
          example: '2022-10-20T00:00:00Z'
          type: string
          format: date-time
          description: Date of operation. <br> Sent with an explicit indication of
            the time zone
        shk_id:
          example: 1239159661
          type: integer
          description: Barcode
        retail_price_withdisc_rub:
          example: 399.68
          type: number
          description: Retail price with agreed discount
        delivery_amount:
          example: 0
          type: integer
          description: Delivery amount
        return_amount:
          example: 0
          type: integer
          description: Return amount
        delivery_rub:
          example: 0
          type: number
          description: Logistics cost
        gi_box_type_name:
          example: Монопалета
          type: string
          description: Box type
        product_discount_for_report:
          example: 399.68
          type: number
          description: Agreed discount
        supplier_promo:
          example: 0
          type: number
          description: Promo code
        rid:
          example: 123722249253
          type: integer
          description: Unique order ID
        ppvz_spp_prc:
          example: 0.1581
          type: number
          description: Discount of regular customer
        ppvz_kvw_prc_base:
          example: 0.15
          type: number
          description: RCW - Reward coefficient of Wildberries, Amount of RCW without
            VAT, % basic
        ppvz_kvw_prc:
          example: -0.0081
          type: number
          description: RCW - Reward coefficient of Wildberries, Total RCW without
            VAT, %
        sup_rating_prc_up:
          type: number
          description: Size of RCW reduction due to rating
        is_kgvp_v2:
          type: number
          description: Size of RCW reduction due to promotion
        ppvz_sales_commission:
          example: -3.74
          type: number
          description: Sales commission before deducting attorney's services, without
            VAT
        ppvz_for_pay:
          example: 376.99
          type: number
          description: To the transfer to the seller for the sold products
        ppvz_reward:
          example: 0
          type: number
          description: Refund for the issuance and return of products to the point
            of issue of orders
        acquiring_fee:
          example: 14.89
          type: number
          description: 'Acquiring costs compensation. <br> WB costs for acquiring
            services: deducted from WB remuneration and does not affect seller''s
            income.

            '
        acquiring_bank:
          example: Тинькофф
          type: string
          description: Name of the acquiring bank
        ppvz_vw:
          example: -3.74
          type: number
          description: WB remuneration without VAT
        ppvz_vw_nds:
          example: -0.75
          type: number
          description: VAT from WB remuneration
        ppvz_office_id:
          example: 105383
          type: integer
          description: Office number
        ppvz_office_name:
          example: Пункт самовывоза (ПВЗ)
          type: string
          description: Delivery office name
        ppvz_supplier_id:
          example: 186465
          type: integer
          description: Partner number
        ppvz_supplier_name:
          example: ИП Жасмин
          type: string
          description: Partner
        ppvz_inn:
          example: '010101010101'
          type: string
          description: Partner's individual tax number
        declaration_number:
          example: ''
          type: string
          description: Number of customs declaration
        bonus_type_name:
          example: Штраф МП. Невыполненный заказ (отмена клиентом после недовоза)
          type: string
          description: 'Justification of fines and surcharges. <br> The field will
            be in the response if a value exists

            '
        sticker_id:
          example: '1964038895'
          type: string
          description: The digital value of the sticker that is attached to the product
            during the order assembly process using the Marketplace system.
        site_country:
          example: RU
          type: string
          description: Country of sale
        penalty:
          example: 231.35
          type: number
          description: Fines
        additional_payment:
          example: 0
          type: number
          description: Surcharges
        rebill_logistic_cost:
          example: 1.349
          type: number
          description: 'Compensation of transportation costs The field will be in
            the response if there is a value.

            '
        rebill_logistic_org:
          example: ИП Иванов Иван Иванович(123456789012)
          type: string
          description: "Organizer of transportation The field will be in the response\
            \ if there is a value          \n"
        kiz:
          example: "0102900000376311210G2CIS?ehge)S\x1D91002A\x1D92F9Qof4FDo/31Icm14kmtuVYQzLypxm3HWkC1vQ/+pVVjm1dNAth1laFMoAGn7yEMWlTjxIe7lQnJqZ7TRZhlHQ=="
          type: string
          description: 'Marking code. <br> The field will be in the response if value
            exists

            '
        srid:
          example: 711ab8cb94e040f98b3804e5f331bf7a_r
          type: string
          description: 'The unique identifier for the order. Note for those using
            the Marketplace API: `srid` is equal to `rid` in assembly tasks methods
            responses.

            '
  parameters:
    dateFrom:
      in: query
      name: dateFrom
      schema:
        type: string
        format: RFC3339
      required: true
      description: 'Date and time of last change on the product.<br> Date format:
        RFC3339. You may send date or date with time.  Time could be specified in
        seconds or milliseconds.<br> The time stands in Moscow time zone (UTC+3).
        <br>Examples: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345`
        <li> `2017-03-25T00:00:00` </ul>

        '
    flag:
      in: query
      name: flag
      schema:
        type: integer
        default: 0
      required: false
      description: 'If parameter `flag=0` (or it doesn''t exist in requests string),
        then call of API methods returns data,  which value of field `lastChangeDate`
        (date and time of refreshing info of service) is greater or equal to the given
        parameter value  `dateFrom`.  In this case the number of returned rows of
        data varies from 0 to approximately 100,000. <br> If parameter `flag=1`, then
        information about all orders or sales with the date will be uploaded,  that
        equals to the passed parameter `dateFrom` (in this case the time in the date
        doesn''t matter).  Also the number of returned rows of data will be equal
        to the number of all orders or sales that were made on the specified date,
        passed in the `dateFrom` parameter.

        '
  examples:
    TokenMissing:
      description: The token is missing
      value: 'proxy: unauthorized'
    TokenInvalid:
      description: Token invalid
      value: 'proxy: invalid token'
    TokenNotFound:
      description: Token deleted
      value: 'proxy: not found'
    TokenIsNotApplicable:
      description: The token used is not applicable to these methods.
      value: 'Error ae394f96-e258-432d-af13-a53a3d31f8b0: request rejected, unathorized:
        token scope not allowed for this API route'
    CantParseDateFrom:
      description: Request timeout
      value:
        errors:
          - can't parse dateFrom
    RequestTimeout:
      description: Request timeout
      value:
        errors:
          - (api-new) request timeout
    RequestLimitStatistics:
      description: Exceeded the allowed number of requests per unit of time
      value:
        code: 429
        message: error text
paths:
  /api/v1/supplier/incomes:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      security:
        - HeaderApiKey: []
      summary: Supplies
      description: Supplies. Maximum 1 request per minute
      tags:
        - Statistics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Date and time of last change on the supplie.<br> Date format:
            RFC3339. You may send date or date with time.  Time could be specified
            in seconds or milliseconds.<br> The time stands in Moscow time zone (UTC+3).
            <br>Examples: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345`
            <li> `2017-03-25T00:00:00` </ul>

            '
      responses:
        200:
          description: Supplies list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IncomesItem'
              example:
                - incomeId: 12345
                  number: ''
                  date: '2022-05-08T00:00:54'
                  lastChangeDate: '2022-05-08T00:44:15.5'
                  supplierArticle: ABCDEF
                  techSize: '0'
                  barcode: '2000328074123'
                  quantity: 3
                  totalPrice: 0
                  dateClose: '2022-05-08T00:00:00'
                  warehouseName: Подольск
                  nmId: 1234567
                  status: Принято
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/stocks:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: []
      summary: Warehouse
      description: 'WB stock product leftover. The data is updated every 30 minutes.  The
        statistics service does not keep a history of product leftovers, so you can
        only retrieve data about them in ''real time'' mode.

        Maximum 1 request per minute

        '
      tags:
        - Statistics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Date and time of last change on the product.<br> The earliest
            possible value should be entered to get the total leftover, e.g. `2019-06-20`.
            Date format: RFC3339. You may send date or date with time.  Time could
            be specified in seconds or milliseconds.<br> The time stands in Moscow
            time zone (UTC+3). <br>Examples: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59`
            <li> `2019-06-20T00:00:00.12345` <li> `2017-03-25T00:00:00` </ul>

            '
      responses:
        200:
          description: List of products in stock
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StocksItem'
              example:
                - lastChangeDate: '2023-07-05T11:13:35'
                  warehouseName: Краснодар
                  supplierArticle: '443284'
                  nmId: 1439871458
                  barcode: '2037401340280'
                  quantity: 33
                  inWayToClient: 1
                  inWayFromClient: 0
                  quantityFull: 34
                  category: Посуда и инвентарь
                  subject: Формы для запекания
                  brand: X
                  techSize: '0'
                  Price: 185
                  Discount: 0
                  isSupply: true
                  isRealization: false
                  SCCode: Tech
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/orders:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: []
      summary: Orders
      description: "Orders. <br>  Important: storage of data for orders is guaranteed\
        \ for no more than 90 days from the date of order. The data is updated every\
        \ 30 minutes.  The exact time when information was updated in the service\
        \ can be seen in the `lastChangeDate` field. <br> To identify goods from one\
        \ order, as well as sales on them, you should use the `gNumber` field (lines\
        \ with the same value of this field refer to one order) and the number of\
        \ the unique item in the order, the `odid` (`rid`) field. \nMaximum 1 request\
        \ per minute\n"
      tags:
        - Statistics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Date and time of last change on the order.<br> Date format:
            RFC3339. You may send date or date with time.  Time could be specified
            in seconds or milliseconds.<br> The time stands in Moscow time zone (UTC+3).
            <br>Examples: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345`
            <li> `2017-03-25T00:00:00` </ul>

            '
        - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Orders list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdersItem'
              example:
                - date: '2022-03-02T14:34:05'
                  lastChangeDate: '2022-03-02T19:30:16'
                  supplierArticle: '12345'
                  techSize: '0'
                  barcode: '9990016520011'
                  totalPrice: 120.56
                  discountPercent: 0
                  warehouseName: Екатеринбург
                  oblast: Московская
                  incomeID: 123456
                  odid: 12345678
                  nmId: 12345678
                  subject: Респираторы
                  category: Спецодежда и СИЗы
                  brand: wildberries
                  isCancel: false
                  cancel_dt: '0001-01-01T00:00:00'
                  gNumber: '12345678'
                  sticker: ''
                  orderType: Клиентский
        400:
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseErrorStatistics'
              examples:
                CantParseDateFrom:
                  $ref: '#/components/examples/CantParseDateFrom'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/sales:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: []
      summary: Sales
      description: 'Sales and returns. <br> Data storage is guaranteed for no more
        than 90 days from the date of sale. <br> The data updated every 30 minutes.
        <br> The `srid` field should be used to identify the order. <br> 1 line means
        1 sale/return and means 1 item.  <br> Maximum 1 request per minute

        '
      tags:
        - Statistics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Date and time of last change on the sale/return.<br> Date
            format: RFC3339. You may send date or date with time.  Time could be specified
            in seconds or milliseconds.<br> The time stands in Moscow time zone (UTC+3).
            <br>Examples: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345`
            <li> `2017-03-25T00:00:00` </ul>

            '
        - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Sales list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SalesItem'
              example:
                - date: '2022-03-04T18:08:31'
                  lastChangeDate: '2022-03-06T10:11:07'
                  warehouseName: Подольск
                  countryName: Россия
                  oblastOkrugName: Центральный федеральный округ
                  regionName: Московская
                  supplierArticle: '12345'
                  nmId: 1234567
                  barcode: '123453559000'
                  category: Бытовая техника
                  subject: Мультистайлеры
                  brand: Тест
                  techSize: '0'
                  incomeID: 56735459
                  isSupply: false
                  isRealization: true
                  totalPrice: 1887
                  discountPercent: 18
                  spp: 26
                  forPay: 1284.01
                  finishedPrice: 1145
                  priceWithDisc: 1547
                  saleID: S9993700024
                  orderType: Клиентский
                  sticker: '926912515'
                  gNumber: '34343462218572569531'
                  odid: 1003837147757
                  srid: 11.rf9ef11fce1684117b0nhj96222982382.3.0
        400:
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseErrorStatistics'
              examples:
                CantParseDateFrom:
                  $ref: '#/components/examples/CantParseDateFrom'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/reportDetailByPeriod:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: []
      summary: Realization sales report
      description: 'Details to the realization report.  <br> The report contains data
        for the last 3 months. <br> If there is no data for the specified period,
        the method will return `null`. <br> Technical break in the work of the method:
        every Monday from 3:00 AM to 4:00 PM. <br> <a href="../../excel_save/en/index.html">Manual:
        Save statistics by Excel</a><br> Maximum 1 request per minute

        '
      tags:
        - Statistics
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Starting date of the report.<br>  Date format: RFC3339. You
            may send date or date with time.  Time could be specified in seconds or
            milliseconds.<br> The time stands in Moscow time zone (UTC+3). <br>Examples:
            <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345`
            <li> `2017-03-25T00:00:00` </ul>

            '
        - in: query
          name: limit
          schema:
            type: integer
            default: 100000
          required: false
          description: The maximum number of report rows returned by the method. Cannot
            be more than 100000.
        - in: query
          name: dateTo
          schema:
            type: string
            format: date
          required: true
          description: Report end date
        - in: query
          name: rrdid
          schema:
            type: integer
          required: false
          description: "The unique ID of the report line. Required to receive the\
            \ report in parts.\n<br>\nReport loading must start with `rrdid = 0` and\
            \ on subsequent API calls, pass the `rrd_id` value in the request from\
            \ the row line received as a result of the previous call. \n<br>\nThus,\
            \ to load a single report, you may need to call the API until the number\
            \ of rows returned is zero.\n"
      responses:
        200:
          description: List of sold items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DetailReportItem'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                  - $ref: '#/components/schemas/Response429'
              examples:
                TechnicalBreak:
                  value: 'Технический перерыв в работе метода: каждый понедельник
                    с 3:00 до 16:00.'
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
